### ISSUE TITLE
sw6.4-production requires composer 2

### ISSUE THREAD

**Issue by ROBJkE** [shyim/shopware-docker#101]
**Describe the bug**
I installed shopware production template 6.4.1.0.
Then enter the shell and want to `bin/build.sh`
An error showed up tells me it requres composer 2. I've checked `composer -v` and version `1.10.22` is given.
How do i update / change to composer version 2?

**To Reproduce**
1. Install Shopware Production 6.4.1.0
2. Enter the Container Shell `swdc shell`
3. Go to my project folder and try to run `bin/build.sh`
4. Error shows up (Screenshot)

**Screenshots**
![image](https://user-images.githubusercontent.com/26817419/122545994-c9f0b300-d02e-11eb-92a8-3d8cc53e76bf.png)

**Environment:**
- Ubuntu 20.04
- Docker Version: 20.10.2
- docker-compose version 1.25.0

**Comment by ROBJkE** [comment]
Found out that `composer2` command exists.
So i set an alias `alias composer="composer2"` in the local `~.bashrc`
Now i get version `2.1.3` if i run `composer` in the shell.

But if I run `bin/build.sh` again the error remains the same. weird.

**Comment by shyim** [comment]
alias does not help. We will need to built a new fuckup to fix that...

**Comment by shyim** [comment]
Fixed with https://github.com/shyim/shopware-docker/commit/a869efb543b7a676f7351b772873cb3a464badd5

Update your images with swdc update-images

**Comment by ScottA38** [comment]
@shyim I had this issue on `b7ca5e29d8037943f564a4e439490e2a365645e0`.
I tried:
`swdc update-images`
Rebooting swdc
In the end I did:
```
swdc shell-root;
cd /var/www/html/[project-name];
composer self-update --2
```
