### ISSUE TITLE
How can I change the idekey from xDebug?

### ISSUE THREAD

**Issue by Psycc** [shyim/shopware-docker#104]
I'm using this solution under WSL 2. Everything works so far.
But when I want to use xDebug with VS Code, it doesn't work. There is a Connection when I run `telnet 0.0.0.0 9000` on Ubuntu, but I think it's because the idekey is set to `PHPSTORM`.

Is there any possibility to make it run?

**Comment by shyim** [comment]
You should be able to set the ide key there too

**Comment by Psycc** [comment]
But where? I dont find any option for that.

**Comment by shyim** [comment]
the idekey seems optional on this setup https://github.com/xdebug/vscode-php-debug/issues/572

**Comment by Psycc** [comment]
Hm okay. To be sure, how can I debug a 500 Error on a product page with the following error?
`Object of class Shopware\Core\Checkout\Cart\Price\Struct\PriceCollection could not be converted to string`

**Comment by shyim** [comment]
APP_ENV=dev?

**Comment by Psycc** [comment]
APP_ENV=dev is already set.
