### ISSUE TITLE
PDF generated is empty after updating image

### ISSUE THREAD

**Issue by zaifastafa** [shyim/shopware-docker#105]
**Describe the bug**
As already discussed with you on slack, the PDF generated is empty after the images are updated. So just creating an issue for easier tracking. 

**Expected behavior**
PDF is created with proper content

**Comment by shyim** [comment]
Should be fixed now again

![image](https://user-images.githubusercontent.com/6224096/125137548-37af6c80-e10d-11eb-935e-eda0bdbd9939.png)
