### ISSUE TITLE
Improve support of Shopware 6 without template

### ISSUE THREAD

**Issue by shyim** [shyim/shopware-docker#106]
As of this week its possible to setup Shopware 6 just with the platform repository.

We need to tweak some commands like check to work there too

**Comment by zaifastafa** [comment]
Can you please explain this in the README file too? We won't need to clone the development template anymore? Is that what you mean?

**Comment by shyim** [comment]
Updated here https://github.com/shyim/shopware-docker/wiki/Usage

Yes platform only works since two weeks
