### ISSUE TITLE
db dump and restore via swdc

### ISSUE THREAD

**Issue by zaifastafa** [shyim/shopware-docker#109]
### Feature request

We can go into the `mysql` container and then run the `mysqldump` command, but it would be great if we can directly import and dump database via `swdc` similar to what we can do with `ddev`. 

Also if we can have the option of the resetting/removing the `DEFINER` during the `db` import, it would be great. This would especially help when importing a live/staging system to our local database.

**Comment by shyim** [comment]
Hey,

you don't need to go the MySQL Container. Just place the sql file under Code/snapshots/[project-name].sql and run `swdc rsnap [project-name]`

It currently doesnt strips definers :thinking: but could be a good way :D

**Comment by shyim** [comment]
Can you provide me a file with definers? @zaifastafa . Files generated by `swdc snap xx` does not contain definers 🤔
