### ISSUE TITLE
docker-compose version configurability or automation

### ISSUE THREAD

**Issue by creative-resort** [shyim/shopware-docker#114]
**Is your feature request related to a problem? Please describe.**
SWDC uses a hard-coded version "3.7". Even installing the latest docker and docker-compose via apt resulted in an incompatibility. Changing the up.sh file to use version "3.6" solved the issue.

**Describe the solution you'd like**
I'd like to propose an option to configure a custom docker-compose version, or an automatic detection of the best compatible version.

**Additional context**
![2021-08-19_173328](https://user-images.githubusercontent.com/12367437/130097852-02e604fd-b469-499e-b7ec-a5ed6b2d9f15.png)

**Comment by shyim** [comment]
You should use this guide to install docker-compose https://docs.docker.com/compose/install/. It should work then directly

**Comment by shyim** [comment]
Updated there https://github.com/shyim/shopware-docker/wiki/Installation
