### ISSUE TITLE
Wiki improvement

### ISSUE THREAD

**Issue by creative-resort** [shyim/shopware-docker#117]
### Discussed in https://github.com/shyim/shopware-docker/discussions/116

<div type='discussions-op-text'>

<sup>Originally posted by **creative-resort** August 19, 2021</sup>
From the Wiki, page
https://github.com/shyim/shopware-docker/wiki/Command-List
it is unclear how these commands are used and from where they are accessed.

Can you please include more detailed instructions, with an example that shows how exactly a command of a specific module is addressed?</div>

**Comment by shyim** [comment]
I have answered in Discussions :)
