### ISSUE TITLE
Making changes in images / configuration

### ISSUE THREAD

**Issue by zaifastafa** [shyim/shopware-docker#118]
Hey if we want to test some server configuration scenario, is that possible to do via swdc ? 

For e.g. I want to check some functionality of the shop if a particular module is disabled or not available, in my case `proc_open` is sometimes disabled in some shops due to security concerns. If I want to test that out in swdc, where can I make the configuration / setup related changes to see the behavior of the shop? 

The `proc_open` is just an example, but in general, since we are using pre-built images, how can I make changes on the image level? Can you also provide a wiki to extend images to enable/disable/install/remove modules and stuff?

**Comment by shyim** [comment]
php.ini works now by just having a php.ini file in the project with your config

**Comment by shyim** [comment]
Create a `.swdc/Dockerfile` file in your project

```
FROM ghcr.io/shyim/shopware-docker/6/nginx:php74

RUN install-php-extensions ssh2
```
