### ISSUE TITLE
Message about install jq / Error about python not found

### ISSUE THREAD

**Issue by bjoern-flagbit** [shyim/shopware-docker#132]
**Message during storefront-build:**
`Cannot check extensions for required npm installations as jq is not installed`

Could you pls install jq on the docker image?

Another message I was seeing is:
`gyp ERR! stack Error: Could not find any Python installation to use`

Maybe Python is also needed. Not sure about this.

I execute storefront-build on the cli docker image.

**Comment by shyim** [comment]
thats wayne. it downloads afterwards the binary. so the error is okay
