### ISSUE TITLE
Cannot start mysql image in WSL2

### ISSUE THREAD

**Issue by khanh-vu** [shyim/shopware-docker#136]
**Describe the bug**
I cannot start mysql image in Windows 10 (WSL2)
the version used: ghcr.io/shyim/shopware-docker/mysql:8
After `swdc up` done, mysql image will be crashed. 
**Screenshots**
![image](https://user-images.githubusercontent.com/26863312/141885637-7b053d3e-f8f5-49b1-934a-45806a4559bd.png)
**Environment:**
 - OS: Windows 10 (WSL2 Ubuntu 18.04)
 - Docker Version: 

Please help with this issue.
Thank you.

**Comment by shyim** [comment]
Does this problem still exists?
