### ISSUE TITLE
Installation of 6.3.5.4 fails with SHOPWARE_INSTALL=1

### ISSUE THREAD

**Issue by daniel-memo-ict** [shyim/shopware-docker#142]
**Describe the bug**
Recently updated swdc to the latest master. Now when I try installing an older version, for example 6.3.5.4, the migrations fail at a certain point, stating that "MigrationStep::isInstallation should return bool, string returned"
Commenting out https://github.com/shyim/shopware-docker/blob/master/modules/platform/build.sh#L34 restores functionality.

I've noticed that v1 is now the default branch, and I will switch to that one. This line does not yet appear to be in that branch, and I'm not sure if it will be added in the future. But just a heads-up that this will fail installation of (slightly) older Shopware versions.

**To Reproduce**
1. Clone shopware dev template
2. Switch to v6.3.5.4 tag
3. Do an swdc build

**Expected behavior**
Migrations should execute normally

**Screenshots**
![image](https://user-images.githubusercontent.com/84572040/149901241-05a65ef2-0525-424a-b077-43ccf60d05be.png)

**Environment:**
 - Ubuntu 20.04.2
 - Docker Version: 20.10.12, build e91ed57

**Comment by shyim** [comment]
I am blind I can't find the SHOPWARE_INSTALL env in the project here set 🤔

**Comment by daniel-memo-ict** [comment]
It's currently only in the master branch, not in v1.

https://github.com/shyim/shopware-docker/blob/master/modules/platform/build.sh#L34

If I comment out that line everything works normally.

**Comment by shyim** [comment]
Use v1. I forgot to delete the master

**Comment by daniel-memo-ict** [comment]
:laughing: All good, I'll let everyone here know to use v1. But why not merge that into master, if that is the new version?
