### ISSUE TITLE
Using latest v1, trying to install 6.2.1 or 6.1.x fails

### ISSUE THREAD

**Issue by daniel-memo-ict** [shyim/shopware-docker#143]
**Describe the bug**
I needed to test something in a 6.1.x version, for reasons. When it's installing the composer packages it fails because it uses composer 2.2, and one of the packages explicitly requires composer 1.x.
This happens for all versions up to and including 6.2.1.

**To Reproduce**
1. Clone the development template
2. Switch the git branch to tag 6.1.5.
3. Run swdc build

**Expected behavior**
Expected it to just install, using composer 1.x instead of 2.x.

**Screenshots**
(For 6.2.1, latest version that can't be installed. 6.2.2 is fine.)
![image](https://user-images.githubusercontent.com/84572040/152545500-991d8460-179e-4c80-ac94-9ea73ecd8afc.png)

**Environment:**
 - OS: Ubuntu 20.04
 - Docker version 20.10.12, build e91ed57

**Comment by shyim** [comment]
Will be fixed with https://github.com/shyim/shopware-docker-images/commit/5c243279c26b62d8c8da5382187675b12babf7d7
