### ISSUE TITLE
Restart failed after one week

### ISSUE THREAD

**Issue by Chichis** [shyim/shopware-docker#144]
Hi shyim,

i got an error after i want to continued to develop something for shopware. Now i always got this error, if i restart the container.

![image](https://user-images.githubusercontent.com/15788657/156796801-6054fdde-330e-45d2-b227-44fb8a812758.png)

**Environment:**
 - OS:  Ubuntu 20.04
 - Docker Version:  4.5.1

**Comment by shyim** [comment]
something is blocking the port
```
> netstat -tulpen
```

**Comment by Chichis** [comment]
![image](https://user-images.githubusercontent.com/15788657/156799744-b43827af-6a3b-43dc-9b4a-0562c8a789b0.png)
 hmm ...

**Comment by shyim** [comment]
run it with sudo

**Comment by Chichis** [comment]
getting the same error

![image](https://user-images.githubusercontent.com/15788657/156803561-e5585897-cce1-46c2-aa5b-5af86d87eae1.png)

thanks for your fast reply :)

**Comment by shyim** [comment]
I mean `sudo netstat -tulpen` :D

**Comment by Chichis** [comment]
![image](https://user-images.githubusercontent.com/15788657/156803895-8511e5d1-40e4-4b8a-8fda-df5fb0c1de0e.png)
 with started containers and without

**Comment by shyim** [comment]
Do you have a local mysql server installed?

**Comment by shyim** [comment]
ahh nvm

**Comment by shyim** [comment]
which docker version do you have installed? can you run `docker -V`

**Comment by Chichis** [comment]
![image](https://user-images.githubusercontent.com/15788657/156805065-3d3d06b8-2f65-4a9f-b4e6-f9a4df33a51b.png)

yes but it wasnt started

**Comment by Chichis** [comment]
@shyim hi, do you had an another idea?

**Comment by shyim** [comment]
I have no idea 🙈 . Maybe solved in the past time?
