### ISSUE TITLE
admin-watch not stopping properly

### ISSUE THREAD

**Issue by zaifastafa** [shyim/shopware-docker#145]
HI, It seems the admin-watch worker is not closing properly. When the admin-watch is active, I close it with Ctrl + X it does not stop. Then I close it with Ctrl + Z then it says stopped. But when doing admin-watch again, it says the
```
ERROR: error while removing network: network shopware-docker_default id a620a61a1a91d792e01f9cf644ac16d77470a828f524b13a31ab062620202ddb has active endpoints
```
and then I have to restart the docker service to clear this orphan

**Comment by daniel-memo-ict** [comment]
Can confirm, have similar problem. Still works normally with Shopware 6.4.7, so I'm assuming it's to do with the node update to v16?

**Comment by zaifastafa** [comment]
@shyim any idea about this?
