### ISSUE TITLE
Support HTTPS in watchers

### ISSUE THREAD

**Issue by tinect** [shyim/shopware-docker#147]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when starting the watchers within cloud-dev (you know the stuff :-) ). The watcher is always using port 80 which doesn't work on an environment which just works on https.

**Describe the solution you'd like**
Remove the port :-)

**Comment by shyim** [comment]
is USE_SSL_DEFAULT set to true in the .env?

**Comment by zaifastafa** [comment]
This env variable only sets the https on the sales channel domain I think. I cannot get the SSL to work either even if this check is set.

**Comment by tinect** [comment]
it is set to true :-(

**Comment by shyim** [comment]
I am pretty sure I had it working with this reverse proxy setting https://github.com/shyim/cloud-dev#example-traefik-labels-recommended

**Comment by shyim** [comment]
As we talked, this needs to be fixed in Shopware itself with the sockPort
