### ISSUE TITLE
/usr/bin/env: `node`: No such file or directory

### ISSUE THREAD

**Issue by LiaraAlis** [shyim/shopware-docker#148]
When I try run `admin-init`, `admin-build` or something like that, i always get:
`/usr/bin/env: 'node': No such file or directory`

It happens with every container but node is working inside `cli` container. Running scripts in `bin/` directly works without problems.

**Comment by shyim** [comment]
Can you update swdc and update all images `swdc update-images`

**Comment by LiaraAlis** [comment]
@shyim I already did this. It doesn't help. :(

**Comment by zaifastafa** [comment]
@shyim this is the problem I mentioned to you on slack as well. I think for me this happens specifically for older versions of shopware.

**Comment by shyim** [comment]
Which PHP versions are you all using?

**Comment by zaifastafa** [comment]
Wait I think my issue is slight different but related to node only #146

**Comment by LiaraAlis** [comment]
@shyim I'm using `php8.0-xdebug`

**Comment by shyim** [comment]
what is the complete docker image name?

**Comment by LiaraAlis** [comment]
@shyim `ghcr.io/shyim/shopware-docker/6/nginx` with tag `php80-xdebug`

**Comment by LiaraAlis** [comment]
@shyim Any updates here?

**Comment by LiaraAlis** [comment]
Problem still exists, unfortunately. :(

**Comment by LiaraAlis** [comment]
Problem fixed myself. It was not a problem of the script.
For some reason, my local repository was not up to date although git told me that it was. :/
I noticed that after manually compared `functions.sh` with the one here in github.
