### ISSUE TITLE
admin watch / build commands for older versions 

### ISSUE THREAD

**Issue by zaifastafa** [shyim/shopware-docker#150]
admin-watch and admin-build commands do not work for shopware 6.3 (6.3.5.4) 

![image](https://user-images.githubusercontent.com/24492269/168968232-0541e093-d967-4c13-b7df-84649aba2516.png)

**Comment by shyim** [comment]
https://github.com/shyim/shopware-docker/commit/1849c3b511a91d1dc3e95442673ff1b31c40fd7d

create a `.nvmrc` and write into it 12 and try again

**Comment by zaifastafa** [comment]
@shyim the build compiles now, but the watch URL does not work. It shows the message: 

(node:56) [DEP0131] DeprecationWarning: The legacy HTTP parser is deprecated.
ℹ ｢wds｣: Project is running at http://0.0.0.0:8181/

If I use `admin-sw63.dev.localhost` -> it gives 503 service temporarily unavailable page.

**Comment by shyim** [comment]
in old versions its localhost:8181
