### ISSUE TITLE
Incorrect completion fallback directory

### ISSUE THREAD

**Issue by rvveber** [shyim/shopware-docker#151]
In case of a non-bash shell, as fallback, the completion.sh wants to access the modules folder inside the ~/Apps/shopware-docker folder.

If a user follows the installation tutorial, where you are instructed to install into the Documents folder - the fallback folder should instead be the ~/Documents/shopware-docker folder.

By changing this path from Apps to Documents i was able to get completion working in my zsh shell.

It also might be worth a thought to customize the install directory and use a variable for fallback directory.

**Comment by shyim** [comment]
Do you have experience how to get the path on zsh? 😂 

I hate that hard-code doo 😭

**Comment by shyim** [comment]
okay it was easier as expected lol https://github.com/shyim/shopware-docker/commit/a14fe65fe46135a0e8ab4a7708c7da7aef891243

**Comment by rvveber** [comment]
Nice! :D 🎊
