### ISSUE TITLE
swdc storefront-watch can't find shopware-docker_cli_1

### ISSUE THREAD

**Issue by rvveber** [shyim/shopware-docker#153]
swdc storefront-watch shop
Error: No such container: shopware-docker_cli_1
Error: No such container: shopware-docker_cli_1

Maybe because container is called `shopware-docker-cli-1` ?

**Comment by shyim** [comment]
Do you use compose v2?

**Comment by rvveber** [comment]
Yes v2.5.1

**Comment by rvveber** [comment]
Actually, i think that is v1, the versioning is just misleading

**Comment by shyim** [comment]
Can you upgrade to v2?

**Comment by rvveber** [comment]
So i created an alias from `docker-compose` to `docker compose` which is v2 syntax and therefore all instances should run on v2, I still get the same error though.
I have tried removing `/tmp/swdc-docker-compose.yml` and swdc up again, but the starting container is still `-cli-1` and in the storefront-watch shortcut it references `_cli_1`

The name of my shop project includes an underscore. client_shop
Maybe that could cause an issue?

**Comment by rvveber** [comment]
Correction! the command throwing this error is storefront-watch not storefront-build... 
My bad XD sorry its late..

**Comment by shyim** [comment]
let me look after league game xD

**Comment by shyim** [comment]
häää looks same for me

**Comment by shyim** [comment]
https://github.com/shyim/shopware-docker/commit/462ef4cf1d926a8ed9f5c35f5c311a758b325aa5

**Comment by shyim** [comment]
should be fixed xD

**Comment by rvveber** [comment]
Good job! :D
