### ISSUE TITLE
.htaccess file not working

### ISSUE THREAD

**Issue by cmg193** [shyim/shopware-docker#154]
**Describe the bug**
Any change inside /project/public/.htaccess are being ignored.

**To Reproduce**
1. add "deny from all" inside a shopware folder "...project/public/.htaccess"
2. page is still loading

**Expected behavior**
I expect to see my .htaccess changes in action.

**Screenshots**

**Environment:**
 - OS: Windows WSL (Ubuntu 20.04)
 - Docker Version: 20.10.5

**Additional context**
If I am not see something, or do something wrong, just let me know. 

Thanks.

**Comment by shyim** [comment]
Hey

the images are by default nginx, you can switch it with in your `.config/swdc/env`

```
VHOST_[FOLDER_NAME_UPPER_CASE]_IMAGE=ghcr.io/shyim/shopware-docker/6/apache:php74-xdebug
```

**Comment by cmg193** [comment]
Oh, 
my bad. 
but adding this line gives me following error:

line:
![image](https://user-images.githubusercontent.com/56188324/170004512-1b3db327-177a-45d5-8900-4efaf656a912.png)
error:
![image](https://user-images.githubusercontent.com/56188324/170004629-2ead4782-9646-4295-ac92-d0455cf2021b.png)

**Comment by shyim** [comment]
Can you try `ghcr.io/shyim/shopware-docker/6/apache:php74`

**Comment by cmg193** [comment]
Yep, worked! Thanks a lot!
