### ISSUE TITLE
Dashes in project name might create issues.

### ISSUE THREAD

**Issue by rvveber** [shyim/shopware-docker#159]
Reproduce: 

- create project with dashes in name e.g. project-demo
- Do swdc snap project-demo

mysql error: -demo not found.

**Comment by rvveber** [comment]
Also it's impossible to reference FOLDER_NAME in ENV Vars if they have dashes in them

**Comment by shyim** [comment]
I guess normalizing to underscore would work 🤔

**Comment by rvveber** [comment]
Problem is just, that underscore characters are not permitted in domain names in accordance with RFC 1035, which only allows letters, digits and hyphens. This creates problems with e.g. chromes internal password filling, as it is not able to recognize a URL with an underscore.

**Comment by shyim** [comment]
EWWWWWWWWWWW

so when a folder contains underscore we have to rewrite it to minus
when a folder contains minus the env has to be underscore

**Comment by rvveber** [comment]
🤣🤣 
Yeah, major turn off

**Comment by swsrmes** [comment]
@color-space On the current `v1` branch I don't have this issue any more
```zsh
srmes ~swdc-dev (v1 !?) % swdc snap shopware-blank                     
mysqldump: [Warning] Using a password on the command line interface can be insecure.
srmes ~swdc-dev (v1 !?) %
```
Can this be closed?

**Comment by shyim** [comment]
I will close this then
