### ISSUE TITLE
XDebug not working on SW5 projects

### ISSUE THREAD

**Issue by rvveber** [shyim/shopware-docker#161]
When using a SW5 Project and enabling XDEBUG as followed in the Wiki
We can only see "File not found." in the frontend.

**Comment by shyim** [comment]
But you replaced the 6 in the image name with 5 right?

🤔

**Comment by rvveber** [comment]
lmao, i did indeed not see this 6.
Corrected it, xdebug gets loaded, but to configure, the php.ini isn't loaded
In project root, right?

**Comment by shyim** [comment]
It should be auto configured. whats your environment? yes with a php.ini file in root you can configure it

**Comment by rvveber** [comment]
I'm on vscode, i imagine i need to configure the xdebug.idekey to match my IDE.
but dunno, i have never really worked with xdebug before, this is my php.ini

```
zend_extension=xdebug.so

xdebug.mode=debug
xdebug.start_with_request=yes
xdebug.discover_client_host=true
xdebug.remote_cookie_expire_time=3600
xdebug.remote_enable=on
xdebug.remote_autostart=on
xdebug.remote_connect_back=on
xdebug.remote_host=project.dev.localhost
xdebug.remote_port=9000
xdebug.idekey=VSCODE
```

All i know is that, those values are not beeing applied when i output phpinfo()

vscodes xdebug launch.json
```
{"version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for Xdebug",
            "type": "php",
            "request": "launch",
            "port": 9000,
            "pathMappings": {
                "/var/www/html/project": "${workspaceFolder}"
            }
        }
    ]}
```

**Comment by rvveber** [comment]
Oh and i'm on arch linux btw. No WSL hacks relevant

**Comment by shyim** [comment]
I never used vscode for xdebug always phpstorm. have no idea sorry 🙈

**Comment by rvveber** [comment]
Okay NVM, xdebug works, php.ini DOES get applied,
just xdebug options don't, because apparently you don't put xdebug options into a php.ini file?

Not sure, but i imagine you could work around that with including a xdebug configuration file location via php.ini. 

Thank you for the help!
