### ISSUE TITLE
Error on fresh installation: address already in use

### ISSUE THREAD

**Issue by rammi22** [shyim/shopware-docker#163]
**Describe the bug**
System: Ubuntu 22.04

With a new installation and `swdc up` the system deamon response with error:
`$ swdc up
[+] Running 0/1
 ⠙ Container shopware-docker-mysql-1  Starting                                                                                                                                                           0.1s
Error response from daemon: driver failed programming external connectivity on endpoint shopware-docker-mysql-1 (15892f99ed64a676161b0b127283339a867e77e7ee5e91b4f8fa1609cef247f6): Error starting userland proxy: listen tcp4 0.0.0.0:3306: bind: address already in use
`

**To Reproduce**
1. following install construction
2. run `swdc up`

**Expected behavior**
no error on a fresh installation

**Screenshots**
`swdc up
[+] Running 0/1
 ⠙ Container shopware-docker-mysql-1  Starting                                                                                                                                                           0.1s
Error response from daemon: driver failed programming external connectivity on endpoint shopware-docker-mysql-1 (15892f99ed64a676161b0b127283339a867e77e7ee5e91b4f8fa1609cef247f6): Error starting userland proxy: listen tcp4 0.0.0.0:3306: bind: address already in use
[+] Running 4/6
 ⠿ Container shopware-docker-smtp-1         Started                                                                                                                                                      1.1s
 ⠿ Container shopware-docker-adminer-1      Started                                                                                                                                                      1.2s
 ⠿ Container shopware-docker-proxy-1        Starting                                                                                                                                                     1.4s
 ⠿ Container shopware-docker-cli-1          Started                                                                                                                                                      1.4s
 ⠿ Container shopware-docker-start_mysql-1  Recreated                                                                                                                                                    0.0s
 ⠇ Container shopware-docker-mysql-1        Starting                                                                                                                                                     0.8s
Error response from daemon: driver failed programming external connectivity on endpoint shopware-docker-proxy-1 (713e7352c47479317dda12f3c82c22ec089a9a40069ff15eb98ea64c52b72523): Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use

`

**Environment:**
 - OS: Ubuntu 22.04 LTS
 - Docker Version: 20.10.17, build 100c701

**Comment by shyim** [comment]
your port 3306, 80 is bound :D

**Comment by rammi22** [comment]
> your port 3306, 80 is bound :D

Sorry , but i dont understand. Can yo maybe extend your answer. Ther is no explanation in the docu about ports and its settings

**Comment by shyim** [comment]
some program is using that port already https://stackoverflow.com/questions/19071512/socket-error-errno-48-address-already-in-use
