### ISSUE TITLE
Add APCu

### ISSUE THREAD

**Issue by Zerotask** [shyim/shopware-docker#166]
**Is your feature request related to a problem? Please describe.**
We'd like to use APCu for caching and therefore it would be great to have APCu available.

**Comment by shyim** [comment]
You can install any extension like so https://github.com/shyim/shopware-docker/wiki/Project-specific-Configuration#installing-docker-php-extensions-sample

**Comment by Zerotask** [comment]
> You can install any extension like so https://github.com/shyim/shopware-docker/wiki/Project-specific-Configuration#installing-docker-php-extensions-sample

Thank you for pointing that out.
Although I'm totally aware of the possibilities, but I prefer using your standard image.
So is there any reason to not add APCu? It could be configurable via an env var which is off by default.

**Comment by shyim** [comment]
It should not hurt let me a moment :D

**Comment by shyim** [comment]
Here :) https://github.com/shyim/shopware-docker-images/commit/59898e4d0e7db58367a7a3d8c5f3ae6bf24c9adc

**Comment by Zerotask** [comment]
> Here :) [shyim/shopware-docker-images@59898e4](https://github.com/shyim/shopware-docker-images/commit/59898e4d0e7db58367a7a3d8c5f3ae6bf24c9adc)

Awesome! Can you add it to https://github.com/shyim/shopware as well? :)

**Comment by shyim** [comment]
I have added it here

https://github.com/shyim/shopware/actions/runs/3284997607

That will take like 2 hour to build and then all shopware images have to been build 🙈 

I need a native arm64 runner 😢
