### ISSUE TITLE
Old branches not working 

### ISSUE THREAD

**Issue by rammi22** [shyim/shopware-docker#169]
**Describe the bug**
Project build with `swdc create-project MyProject` only works on newest branch (6.99.99.0, HEAD, trunk)

**To Reproduce**

1. console: `swdc create-project MyProject`
2. console `swdc up MyProject`
4. console: `swdc build MyProject --without-demo-data`
5. checkout branch 6.1 (trying 6.2, 6.3*, 6.4.*)
6. console: `swdc up MyProject`
7. console: `swdc admin-watch MyProject`
8. different errors on each branch

**Expected behavior**
work on provided branches

**Screenshots**
e.g. checkout branch 6.2
```
rammi@rammi-laptop-i7:~/Code/shopware-sandbox$ swdc admin-watch shopware-sandbox
Installing Node v12.22.12 (x64)
warning: Version already installed at "/nvm/.debian-fnm/node-versions/v12.22.12"
Using Node v12.22.12
Using Node v6.17.1
./modules/platform/admin-watch.sh: line 12: bin/console: No such file or directory
./modules/platform/admin-watch.sh: line 13: bin/console: No such file or directory

> administration@1.0.0 dev /var/www/html/shopware-sandbox/src/Administration/Resources/app/administration
> node build/dev-server.js "http://shopware-sandbox.dev.localhost"


To use this template, you must update following to modules:

  npm: 3.10.10 should be >= 6.5.0


npm ERR! Linux 5.15.0-48-generic
npm ERR! argv "/nvm/.debian-fnm/node-versions/v6.17.1/installation/bin/node" "/home/dev/.local/state/fnm_multishells/22_1665481491087/bin/npm" "run" "--prefix" "src/Administration//Resources/app/administration/" "dev" "--" "http://shopware-sandbox.dev.localhost"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! administration@1.0.0 dev: `node build/dev-server.js "http://shopware-sandbox.dev.localhost"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the administration@1.0.0 dev script 'node build/dev-server.js "http://shopware-sandbox.dev.localhost"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the administration package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/dev-server.js "http://shopware-sandbox.dev.localhost"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs administration
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls administration
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/shopware-sandbox/npm-debug.log

```

**Environment:**
 - OS: [e.g. Ubuntu 22.04]
 - Docker Version: 20.10.18

**Comment by shyim** [comment]
Hey,

I have no time to look into fixing Shopware 6.2 installs. Feel free to make a PR or use any other setups. It's not worth the time fixing for so old versions

**Comment by rammi22** [comment]
Hello @shyim  
> Hey,
> 
> I have no time to look into fixing Shopware 6.2 installs. Feel free to make a PR or use any other setups. It's not worth the time fixing for so old versions

I understand your point, but you provide commands, which doesnt work. At least remove this commands or **extend/update your documentation**.

As developer it ist very painfull every time to debug not working but provided but not working tcommands in context of versions.

e.g. 
`swdc admin-jest %Project% %MyPlugin%` does not work

As solution i try to execute the JEST unit test swithin the [jest-preset-sw6-admin](https://github.com/shopware/jest-preset-sw6-admin)  configuration.
The first error pointed out that the provided node version (12.*) are incompatible with the required node version (>= 16.*). So this is a **bug  inside the provided container.**

This creates chained errors...

**Comment by shyim** [comment]
It is open-source. Feel free to contribute and fix it :)
