### ISSUE TITLE
Timezone is not working

### ISSUE THREAD

**Issue by Zerotask** [shyim/shopware-docker#172]
**Describe the bug**
by default TZ is set to Europe/Berlin, although I noticed (via product.updated_at) that it's always -2 h from Europe/Berlin time

**Expected behavior**
Should be same time then Europe/Berlin

**Environment:**
 - Docker Version: shyim/shopware:6.4.16.0-php8.0

**Comment by shyim** [comment]
That's hard-code in Shopware itself as has nothing todo with this setup :)

https://github.com/shopware/platform/blob/08dfd59e0d49ef0f872962b32cd3d8d1f3e3b440/src/Core/Kernel.php#L82

**Comment by Zerotask** [comment]
Any plans to update that in Shopware or is this behavior really wanted from Shopware (if you know that)?

**Comment by shyim** [comment]
Thats wanted. It's a design decision to store only UTC and convert it for a specific user in their time zone. 

The admin itself should convert it always to your datetime zone
