### ISSUE TITLE
how to use the platform module? 

### ISSUE THREAD

**Issue by sition** [shyim/shopware-docker#29]
trying to use swdc build for sw6 but it uses classic mode, how to swich / use the platform mode?

**Comment by shyim** [comment]
Hey, its auto detects it. Did you cloned the Development Repository?

**Comment by sition** [comment]
this one: git clone git@github.com:shopware/platform.git

**Comment by shyim** [comment]
You have to clone development
git clone git@github.com:shopware/development.git

**Comment by sition** [comment]
thanks! will try

**Comment by shyim** [comment]
Is it working?

**Comment by sition** [comment]
yes it is!, tried it on MAC, and it is working on mac, but a bit slow, even if we use :delegated option to mount the volumes. 
we are thinking about changing to ubuntu in the office instead for the windows laptops, but for mac we want to stay on mac.

**Comment by shyim** [comment]
I am recommending all users just to run everything locally. I have used on my last mac setup https://github.com/weprovide/valet-plus

**Comment by shyim** [comment]
I will close then the Issue
