### ISSUE TITLE
Container does not start with xdebug

### ISSUE THREAD

**Issue by zaifastafa** [shyim/shopware-docker#46]
Hi, when using
```
swdc up xdebug
```

with `PHP 5.6` I get this error: 
```
manifest for shyim/shopware-classic-nginx:php56-xdebug not found: manifest unknown: manifest unknown
```

**Comment by shyim** [comment]
Should be fixed when the build is finished from https://github.com/shyim/shopware-docker/commit/125a4c193772c92e1bfb3011331e9cbc604cddee

**Comment by zaifastafa** [comment]
OK, also can you post some documentation regarding the SW6 setup? Executing `swdc build development` runs successfully but when `swdc open development` is executed, it shows `503 Service Unavailable` page instead of the shop.

**Comment by shyim** [comment]
Are you using really PHP 5.6 for SW6?

**Comment by zaifastafa** [comment]
@shyim No, but I am using your setup for development on both versions. I have a separate setup `7.3` for SW6

**Comment by shyim** [comment]
Do you changed the PHP Version per project?

**Comment by zaifastafa** [comment]
Yes I wanted to test something out for SW 5.2 so I had changed the `.env` to install PHP 5.6 and then for the SW 6 development I changed it to PHP 7.3 and doing `swdc up xdebug` after doing `swdc down` so that new image is downloaded for the PHP. 

So no, I was not using PHP 7.3 for Shopware 5.2

**Comment by zaifastafa** [comment]
@shyim 
Getting this related error, even after pulling the latest changes. 

``ERROR: manifest for shyim/shopware-platform-nginx:php56-xdebug not found: manifest unknown: manifest unknown``

I know its due to the `platform` directory but I have the sw6 in the same folder as my other sw5 versions, and since there is just a one `CODE_DIRECTORY` option given in the `env` file. 

So it would be great if you can give an option of defining different root folders for sw5 and sw6 in the `.env` file that way we can organize the installations in different directories. As more likely we are working with multiple versions of Shopware.

**Comment by shyim** [comment]
You should set the `PHP_VERSION` to a most used php version.

When a single folder needs a another PHP Version, overwrite it for it.
Example: Your folder is named: sw510

VHOST_SW510_IMAGE=shyim/shopware-classic-nginx:php56

So only that folder uses that image and not **all**

**Comment by zaifastafa** [comment]
ahan I see! cool! thanks. yes it works. it is so much faster than `psh`. Thanks alot.
