### ISSUE TITLE
Apache Setup

### ISSUE THREAD

**Issue by zaifastafa** [shyim/shopware-docker#47]
Hi @shyim can we have an option of setting up an Apache server as well from within the `.env` file? Sometimes we do not always need an nginx server for e.g if we want to replicate an existing live setup locally.

**Comment by shyim** [comment]
Currently not.
Do you need anything special in the apache setup? I could create a new image for that

**Comment by zaifastafa** [comment]
Would that be compatible with the existing structure and flow? If so then yes that would be much appreciated. Just the regular PHP with xdebug. Ideally it would be awesone for all relevant PHP versions such as 5.6, 7.2 and 7.3, but if it takes too much of your time then just 7.2 would be great.

**Comment by shyim** [comment]
https://hub.docker.com/r/shyim/shopware-classic-apache/tags
https://hub.docker.com/r/shyim/shopware-platform-apache/tags

Can be used with an override of the image. Example:

(SW6 is my folder)
```
VHOST_SW6_IMAGE=shyim/shopware-platform-apache:php72
```
