### ISSUE TITLE
Admin commands doesn't work

### ISSUE THREAD

**Issue by zaifastafa** [shyim/shopware-docker#48]
Hi, so I was developing an administration module and turns out the `swdc admin-build` and `swdc admin-watch` commands do not work.  It just prints out the same command list which we get when executing `swdc`. 

Is there a different way of calling those commands ? I haven't tried the storefront commands yet.

 From within the container shell, we do not have `swdc` available there. So I am running it from the host machine.

Thanks.

**Comment by shyim** [comment]
Which type of shopware 6 installation do you have?

**Comment by zaifastafa** [comment]
It is from the git repository. But instead of using `psh` I use `swdc` commands.

**Comment by shyim** [comment]
which repository? development?

**Comment by zaifastafa** [comment]
Yes, development with a platform repo inside.

**Comment by shyim** [comment]
Did you executed `swdc admin-watch [Folder]`

**Comment by zaifastafa** [comment]
I see. No I didn't check with the folder argument. The usage was not clear. Will try that out. Thanks.
