### ISSUE TITLE
swdc-inside: No such file or directory

### ISSUE THREAD

**Issue by anewarray** [shyim/shopware-docker#50]
I tried to install shopware-docker on wsl. Everything was finde until I tried to build:
./swdc build sw6
Message:
swdc-inside: No such file or directory

**Comment by shyim** [comment]
I have no idea. Never used WSL for that.
swdc-inside is only called inside the docker container.
Can you do swdc shell
and check /opt/swdc exists?

**Comment by anewarray** [comment]
It works now. It was my mistake
for WSL-Installations it is important to clone this repository into your Windows Directory (enable File-Sharing in Docker) and not inside the installed Linux.

**Comment by shyim** [comment]
How is the performance? And which version is currently used 1 or 2?

**Comment by anewarray** [comment]
I use currently 1. There were problems with the persmissions of config/jwt/public.pem (i could not change the permissions). The performance could be better but I will check if the watchers are helping.
