### ISSUE TITLE
Frontend does not load after pulling latest changes

### ISSUE THREAD

**Issue by zaifastafa** [shyim/shopware-docker#51]
Hi @shyim the frontend for SW5 does not load after pulling the latest changes for this repository AND pulling the shopware 5.6 repo. 

When typing `sw5.dev.localhost` it changes to `sw5./` and gives the `site cannot be reached` error. 
The backend however, works properly when typed `sw5.dev.localhost/backend`

Is there anything in the SW5 repo that is maybe conflicting with your setup? 

P.S. I did a `swdc build sw5` after pulling the changes. So I haven't checked if the problem comes with `sw6` too or not, as I have not `build` `sw6` yet.

**Comment by shyim** [comment]
Currently the env inheritance seems not to work.
You need to add to `~/.config/swdc/env`

```
DEFAULT_DOMAIN="dev.localhost"
```

**Comment by zaifastafa** [comment]
@shyim does not seem to be working. It changes to `http://sw5.%22dev.localhost%22/` instead now. I tried removing the `"` around it as well, but didnt make any differennce.

**Comment by shyim** [comment]
Did you run after the change again swdc up?

**Comment by zaifastafa** [comment]
@shyim Yes, I did `swdc down` and then `swdc up xdebug` again.

**Comment by shyim** [comment]
Can you remove it from your config pull again. and try again?

**Comment by zaifastafa** [comment]
@shyim the error is still the same.

**Comment by shyim** [comment]
Okay I have it too. I looking into it. 
You can access the backend with /backend and fix the setting in the settings

**Comment by shyim** [comment]
Is fixed with the attached commit
