### ISSUE TITLE
Using admin-watch I cannot login to the administration

### ISSUE THREAD

**Issue by zaifastafa** [shyim/shopware-docker#53]
Hey, I am using `admin-watch` and the administration opens on port 8181, but when I login, it keeps redirecting me to my login page so I cannot login.

**Comment by zaifastafa** [comment]
OK I can confirm this is not related to my build. The build is compiling successfully, yet I cannot login to the administration.

**Comment by shyim** [comment]
You have to use localhost as host. Its working in core since 6.2

**Comment by zaifastafa** [comment]
So the custom domain wont work for the watch commands. I see. Let me try that and get back to you. Thanks.
