### ISSUE TITLE
Saleschannel Mapping Exception

### ISSUE THREAD

**Issue by zaifastafa** [shyim/shopware-docker#60]
Hi, after doing a build on the latest pull, I get this exception 
```
Unable to find a matching sales channel for the request: http://sw6.dev.localhost/". Please make sure the domain mapping is correct.
```
when loading the storefront. I verified from the admin that the domain url is set for the saleschannel. 

It says unable to find a matching sales channel for the request. 

**EDIT**: It turns out that the recent introduction of HTTP_PORT is causing the problem. It is adding the :80 in the domain URL which fails when opening the storefront.

**Comment by shyim** [comment]
Yup.
Didnt checked the PR sorry fixed with https://github.com/shyim/shopware-docker/commit/028414f648a99cf7e1533fd0c3da7ca0ede037ae
