### ISSUE TITLE
Getting error when pulling the latest nginx-proxy image

### ISSUE THREAD

**Issue by zaifastafa** [shyim/shopware-docker#61]
Pulling proxy (shyim/nginx-proxy:latest)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

After continuing .. 
ERROR: pull access denied for shyim/nginx-proxy, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by shyim** [comment]
You are right :see_no_evil: 
Should be fixed now
