### ISSUE TITLE
Getting bad address 'mysql' error when building containers

### ISSUE THREAD

**Issue by zaifastafa** [shyim/shopware-docker#65]
![image](https://user-images.githubusercontent.com/24492269/95201836-e844b480-07f9-11eb-9f2f-2cbc9b8c0277.png)

I was using mysql:8 image but I saw in the Shopware doc that it is not recommended due to technical issues. So I switched back to 5.7 but now I keep getting this error even after doing docker prune and removing all images/data/volumes. 

I tried official mysql image and also shyim docker mysql 57 but neither of them works.

**Comment by shyim** [comment]
@philipgatzka Did you had this not on your setup? I guess it was dns related stuff

**Comment by zaifastafa** [comment]
So how to resolve this?

**Comment by shyim** [comment]
In /etc/resolv.conf you have a search domain. Maybe remove it. I guess that was it

**Comment by zaifastafa** [comment]
> In /etc/resolv.conf you have a search domain. Maybe remove it. I guess that was it

It is dynamically generated so any changes in that file gets overridden.

**Comment by zaifastafa** [comment]
If I use mysql:8 only then it builds properly. Other than that any version or another image gives this bad address issue.

**Comment by zaifastafa** [comment]
I had to delete the complete repository and then clone it again for it to work.

**Comment by shyim** [comment]
Strange. Did you had changed something?

**Comment by zaifastafa** [comment]
No just started from scratch. Tried different images but it kept giving the bad address issue. So finally I just deleted everything including the repo and then used 5.7 for mysql and it worked

**Comment by shyim** [comment]
As it works. I will close this
