### ISSUE TITLE
Using SOAP requests does not load

### ISSUE THREAD

**Issue by zaifastafa** [shyim/shopware-docker#67]
SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://some-path-here?wsdl' : failed to load external entity. I gogoled a bit, and found that it is due to some SSL issue. So I added the options: 
```
$options = [
            'cache_wsdl' => WSDL_CACHE_NONE,
            'trace' => 1,
            'stream_context' => stream_context_create(
                [
                    'ssl' => [
                        'verify_peer' => false,
                        'verify_peer_name' => false,
                        'allow_self_signed' => true
                    ]
                ]
            )
        ];

        $wsdlUrl = $this->getConfig('apiUrl');
```
But it still does not work. On a live server it is working after adding the `ssl` options, but not on the docker setup.

**Comment by shyim** [comment]
Can you provide an example script? Never used soap since 3 years 😅

**Comment by zaifastafa** [comment]
No unfortunately I cannot disclose that link (client's requirement) but I think you can try any available `?wsdl` url. I tried the cURL as well and it gave "could not resolve host." Seems like it is not able to communicate outside the container for soap requests (even though it is enabled)

**Comment by shyim** [comment]
Test Script:

```php
<?php
$client = new SoapClient("https://www.dataaccess.com/webservicesserver/NumberConversion.wso?wsdl");

var_dump($client->NumberToWords(['ubiNum' => 100]));
```

Output:

```
object(stdClass)#10 (1) {
  ["NumberToWordsResult"]=>
  string(12) "one hundred "
}
```

See no problem so far

**Comment by zaifastafa** [comment]
Hmm, so what could it be that is causing the issue at my end? It is working on a live server but not through my docker setup.

**Comment by zaifastafa** [comment]
It is working now for some reason - weird.
