### ISSUE TITLE
Using SSL_DEFAULT does not create https sales channel domain entry

### ISSUE THREAD

**Issue by zaifastafa** [shyim/shopware-docker#69]
Like the title says, after enabling this in the env, and doing swdc buid sw6, it does not create https entry in the sales channel domain.

**Comment by shyim** [comment]
I could not reproduce it 🙈

**Comment by zaifastafa** [comment]
I will try it again. It was a fresh installation though. But ok will check it again and update the issue accordingly.

**Comment by zaifastafa** [comment]
it worked, but then we do not have a `http` entry. I think using default means the `https` should be default but we should also have a `http` domain, right? And the symfony debug toolbar does not work with SSH. Is it a known issue?

**Comment by shyim** [comment]
The ssl default uses in the installation https for the links. Requests are still possible in both ways http and https. In Shopware 6 some of them will fail, cause the url is not in the sales channel settings.

What do you mean with ssh. Can you create a new issue for that to differentiate that
