### ISSUE TITLE
Using --without-demo-data still creates demo data

### ISSUE THREAD

**Issue by zaifastafa** [shyim/shopware-docker#79]
**Describe the bug**
When using --without-demo-data for the `build` it still generates demo data

**To Reproduce**
1. `swdc build sw6 --without-demo-data`

**Expected behavior**
No demo data is generated

**Screenshots**

**Environment:**
 - OS: Ubuntu 20.04
 - Docker Version: Docker version 19.03.13, build 4484c46d9d

**Additional context**

**Comment by shyim** [comment]
which template are you using?

**Comment by zaifastafa** [comment]
Development

**Comment by shyim** [comment]
Fixed with https://github.com/shyim/shopware-docker/commit/892cfcfc221c8893710c26ed4c3776dddc34c4dd
Seems like I was drunken
