### ISSUE TITLE
A wiki for setting up xdebug with phpstorm with this setup

### ISSUE THREAD

**Issue by zaifastafa** [shyim/shopware-docker#83]
**Is your feature request related to a problem? Please describe.**
I always end up at a breakpoint  at index.php although there is none set there. Even if I step forward, it never reaches my breakpoint, and repeats after reaching `kernel->handle()`.

![image](https://user-images.githubusercontent.com/24492269/107033116-a7c06c00-67d6-11eb-89e0-afeaaa075fc1.png)

**Describe the solution you'd like**
A genereal wiki or guide on how to setup xdebug + phpstorm + swdc

**Describe alternatives you've considered**
A wiki or guide about using it properly with the swdc setup would be great. Have tried different tutorials which all show different things. Some talk about creating Remote Debug, some talk about PHP script. Even then it does what I mentioned above, instead of stopping at my breakpoint.

**Comment by shyim** [comment]
I guess you have this option enabled

![image](https://user-images.githubusercontent.com/6224096/107965216-8d427b80-6faa-11eb-8443-5ecbfabc22f2.png)

**Comment by zaifastafa** [comment]
Yeah I had this enabled 🤦🏼‍♂️
