### ISSUE TITLE
Upgrade to Shopware 6.3.5.1 for Security Fixes

### ISSUE THREAD

**Issue by thomasbeauvais** [shyim/shopware-docker#85]
Thanks for the great work and help with Shopware!

https://www.shopware.com/en/changelog/#6-3-5-1

It seems like there is an update that the Shopware team are really urging that is rolled out for customers. Can you please bump the release? 

Thanks!

**Comment by shyim** [comment]
This repository contains only the docker config and no shopware versions. Do you mean `shyim/shopware`? The CI is running there: https://github.com/shyim/shopware/runs/1854012466

**Comment by thomasbeauvais** [comment]
Oooops, yup! I sure did! Thanks for the correction! Thanks for the release.
