### ISSUE TITLE
Memory exhaustion when running PHPUnit tests

### ISSUE THREAD

**Issue by zaifastafa** [shyim/shopware-docker#88]
**Describe the bug**
It used to work fine, but after the recent changes, am not sure what happened at the image level, but the phpunit tests go into memory exhaustion after ~192 tests. Before I could execute 500+ tests in one go and it used to work fine. 

**To Reproduce**
- Running phpunit tests more than 300

**Expected behavior**
- Should complete all the unit tests execution without memory exhaustion

**Screenshots**
![image](https://user-images.githubusercontent.com/24492269/108469192-a51b4780-72a9-11eb-94d7-54a0bb507650.png)

**Environment:**
 - 7.3-xdebug nginx image
 - mysql: ghcr.io/shyim/shopware-docker/mysql:8

**Additional context**

**Comment by shyim** [comment]
How did you run it

**Comment by zaifastafa** [comment]
Through phpstorm phpunit configuration.

**Comment by shyim** [comment]
the cli container has 4gb memory limit. Use the cli service
